name: deploy

on:
  # Trigger the workflow on push to main branch with changes
  push:
    branches:
    - main

permissions:
  pages: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: open-tyndp-workshops
        channel-priority: strict

    - name: Update environment
      run: |
        conda env update -n open-tyndp-workshops -f environment.yaml
        echo "Run conda list" && conda list

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build open-tyndp-workshops

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: open-tyndp-workshops/_build/html
