name: deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build-and-preview-book:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v5

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: open-tyndp-workshops
        channel-priority: strict

    - name: Update environment
      run: |
        conda env update -n open-tyndp-workshops -f environment.yaml
        echo "Run conda list" && conda list

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build open-tyndp-workshops

    # Deploy the preview
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: open-tyndp-workshops/_build/html